export {
  setPostHogCapture,
  trackOnboardingStarted,
  trackOnboardingCompleted,
  trackHomeViewed,
  trackDailyAssignmentsLoaded,
  trackQuestStarted,
  trackProofUploadStarted,
  trackProofUploadCompleted,
  trackQuestCompleted,
  trackProgressViewed,
  trackStreakExtended,
  trackLevelUp,
  trackArchetypeChanged,
  trackEdgeFunctionFailed,
} from './events';
